In [2]:
# Mount Google Drive to this Notebook instance.
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [1]:
import time
import os
from glob import glob
from pathlib import Path
import math
import numpy as np
import random


def run_os_listdir(directory):
    a = time.time_ns()
    dirname = Path(directory)
    fu = [os.path.join(directory, o) for o in os.listdir(directory) if os.path.isdir(os.path.join(directory, o))]    
    return fu

directory =r"/root//preprocessed/all_preproceeed_codes_by_url"

fu = run_os_listdir(directory)
all_rep_nums = 0
for d in fu:
    sfu = run_os_listdir(d)
    for sd in sfu:
        all_rep_nums +=1

In [2]:
fu

['/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar',
 '/root//preprocessed/all_preproceeed_codes_by_url/.ipynb_checkpoints',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API',
 '/root//preprocessed/all_preproceeed_codes_by_url/SoundCloud API',
 '/root//preprocessed/all_preproceeed_codes_by_url/Wikipedia API',
 '/root//preprocessed/all_preproceeed_codes_by_url/YouTube API',
 '/root//preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Maps API',
 '/root//preprocessed/all_preproceeed_codes_by_url/Facebook API',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google App Engine API',
 '/root//preprocessed/all_preproceeed_codes_by_url/Instagram Graph API',
 '/root//preprocessed/all_preproceeed_codes_by_url/Amazon Product Advertising API',
 '/root//preprocessed/all_preproceeed_codes_by_url/LinkedIn API']

In [3]:
all_rep_nums

938

In [4]:
train_pre = 80
train_rep_nums = math.ceil(train_pre*all_rep_nums/100)
test_rep_nums = all_rep_nums-train_rep_nums
train_rep = []
test_rep = []

In [5]:
fu

['/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar',
 '/root//preprocessed/all_preproceeed_codes_by_url/.ipynb_checkpoints',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API',
 '/root//preprocessed/all_preproceeed_codes_by_url/SoundCloud API',
 '/root//preprocessed/all_preproceeed_codes_by_url/Wikipedia API',
 '/root//preprocessed/all_preproceeed_codes_by_url/YouTube API',
 '/root//preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Maps API',
 '/root//preprocessed/all_preproceeed_codes_by_url/Facebook API',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google App Engine API',
 '/root//preprocessed/all_preproceeed_codes_by_url/Instagram Graph API',
 '/root//preprocessed/all_preproceeed_codes_by_url/Amazon Product Advertising API',
 '/root//preprocessed/all_preproceeed_codes_by_url/LinkedIn API']

In [6]:
for d in fu:
    sfu = run_os_listdir(d)
    if(len(sfu)==0):
        continue
    print(sfu)    
    selected_test = math.ceil(test_rep_nums*(len(sfu)/all_rep_nums))
    all_list = np.arange(len(sfu))
    test = random.sample(range(0, len(sfu)), selected_test)
    train = np.delete(all_list, test)
    for d in test:
        test_rep.append(sfu[d])
    for d in train:
        train_rep.append(sfu[d])

['/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/LastFM', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/Last.fm API', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/.ipynb_checkpoints', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/NetBeansProjects', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/Qualidade', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/LastFm-application', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/jSona', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/MultiClient', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/Player', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/heosnotifscrobbler', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/bachelorHomeworkAndStudy', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/lastfm-ws', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/allJavaProjects', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/mediabrainz-java', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/Mobile-Work', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/angler', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/musicplayer', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/Throwback', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/javay', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/last-fm-java-crawler', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/spring-corenlp', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/playlist-bot', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/TopMusic', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/My-Android-Apps', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/MusicWiki', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/portfolio', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/MuzixApp-Angular-Spring-Mongo', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/MusicMasti', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/M.A.D-Player', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/Walkboy', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/rookit', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/CandyFm', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/NoiseBot', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/lastfm-simple-scrobble-client', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/lastfm-java', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/aTunes', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/HypnosMusicPlayer', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/The-fm', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/material-player', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/fm API', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/LloydsPOC', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/AudioPlayer', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/harmony', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/MusicPlayer', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/ntua-Multimedia', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/TypeaheadSearch', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/MusicApp', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/App-music', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/FMManager', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/Music_Searcher_Test-for-Wipro', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/music', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/resumeSite', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/Isel-Projects', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/musicbrainz-android', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/Muzik', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/MyMusicPlayer', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/SongFinder', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/project', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/srimusic-java', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/Scrobblit', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/MagicCharts', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/DondaChanter', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/MarritLeenstra-pset3_2', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/audio_player_dev_mobile', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/Onix', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/IpodLastfmScrobbler', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/mymusic', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/LastFMAPI', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/MusicPlayer-using-MVC', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/TicktockMusic', '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/SohanCodingTest']
['/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/Teamproject', '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/widgr', '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/calendar-events-processor', '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/google', '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/project-in-house', '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/OdonTO-DO', '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/google-api-libs', '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/sra-project', '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/isst-proy', '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/gerenciador', '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/google-api-java-client-samples', '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/myexperiments', '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/ngcalsync', '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/Hybrid-App-Web', '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/Whirlpool_Android', '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/Starbucks-Schedule-Importer', '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/google-calendar-poc']
['/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Ptesting', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/PostsApp', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/GestionStockSpringBoot', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Gestion_De_Stock', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/.ipynb_checkpoints', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/ImageSearch', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/SpringSocialFlickr', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Gestionstock', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/festive-road-tagging', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/AndroidNetworking_Ass', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/PhotoGalleryModified', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/flickr-api', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/JHgallery', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/structured-topics', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/InstagramLow', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/api_stock_management', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Flickr-Android', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/GestionDeStockMvc', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/GestiondeStock', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/VARpedia', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Gestion_stock_MVC', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/PhotoGalleryWithRxJava', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/flickroauth', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/FlickrLiker', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Gestion_de_stock', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Flickr_App_TDAM_FRC_UTN', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/MyWorkAndAssignments', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/gestion-de-stock-backend', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/oop_nlp', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Photography', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Spring-Boot', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Lab4_Android_Networking', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/flickr', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/flickr_json_app', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Wallpaper', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/CleanItApp', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/MBFlickrDemo', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Projetos-De-Faculdade', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/InventoryManagement', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/camerstock', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/BigPicture', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/flickrfindr', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/proyectoPPII', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/igrisca', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/PruebaJava', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/gestion-bancaire-master', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/epicture', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/int20h', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/MobileOS', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/gestion_stock', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/PhotoGalleryMVVM', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/photosearchapp', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/TestAIA', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Sales-Managements', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/OktaFlickrSpringIntegration_backend', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/stock_management', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/flickr-service', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Java-for-Data-Science', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/imedia24Test', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/googleMap', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/PhotosApp', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/mediasynchronizer', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/HelixiosWall', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/flicking', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Flickr-Findr', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/webService', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Wallpaper_Portal', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/PhotoFlickr', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/GestionDeStock', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/J4DataScience', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Machine-Learning-End-to-Endguide-for-Java-developers', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/TDAM_TPI', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/studies', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/RetrofitFlickrAPI', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/tuto_GET', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/stockmanagement-backend', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/MemoryGame', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/GestionStock', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Journeys', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/projektyStudia', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/gestionStock', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/WallpaperFlicker', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/newMediaLab', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/WallpaperAppByDucMinh', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/FlickrList', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/GestionPaieSpring', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/backend-Ecommerce', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/flickr_gui', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Shakalgram', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/StegHash', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/SpringComplet', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/flickr-groups', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/kubernetes-example-application', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/flicloader', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/book-iot-for-javadeveloper', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/carl-bot', '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/AndroidAssessment']
['/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/phoenix', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/twitter_app', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/misc', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/.ipynb_checkpoints', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/circle-ci', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/twitter-app', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/onesaitplatform-revoluiton-blockchain', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/beunique', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/twitter-bubbles', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/social-searcher', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/spring-twitter-stream', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/twitter_streaming_elk', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/message-gateway', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/moodRing', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/twitter4j-patched', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/minianalytics', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/TwitterLab', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/ara-twitter', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/spring-social-twitter', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/Indian-Premier-League-Data-Analysis', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/MOCAD', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/GraphFromTwitterFollowers', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/TwitterObserver', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/Twitter-Bot', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/awt', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/WebsiteSchema', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/onesaitplatform-revolution-team-work3', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/DSMS_Project', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/TwitterCodingChallenge', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/twitter4j', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/onesaitplatform-revolution-aut-2', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/sentimentAnalysis', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/twitter-miner-v2', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/websiteschema', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/project-bigData', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/cz4034-Grp2-2019s2', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/LetsMine', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/DS_Practica3', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/SpringSocial', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/twitter-search-client', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/lab0-twitter-rest', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/bds_project_workspace', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/LoginSocialNetwork', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/wp-twitter-bot', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/sdn-twitter-graph', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/TwitterGraphTest', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/twitter-services', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/butterfly-effect-stocks', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/onesaitplatform-revolution-dem', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/heckenlights', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/tweeter-kafka-spark-streaming', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/bigfarmathchallenge', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/TwitchArchiver', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/bell-twitter-bot', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/geotweeter-for-android', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/TMDAD-5maquinas', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/twitter-dashboard-hdp', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/JavaPractice', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/twithub', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/oauthhing-with-twitter', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/twitter-poll-app', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/community_detection_evolution', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/Twidere-Android-App', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/dispatcher', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/IF4072-SentimentAnalyser', '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/mephi-dsbda-2020-hw3-stream-api']

In [7]:
print(len(train_rep))
print(len(test_rep))

743
195

In [8]:
train_rep

['/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/LastFM',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/.ipynb_checkpoints',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/NetBeansProjects',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/Qualidade',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/LastFm-application',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/jSona',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/MultiClient',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/Player',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/bachelorHomeworkAndStudy',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/lastfm-ws',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/allJavaProjects',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/Mobile-Work',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/musicplayer',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/javay',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/spring-corenlp',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/TopMusic',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/My-Android-Apps',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/MusicWiki',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/portfolio',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/MuzixApp-Angular-Spring-Mongo',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/MusicMasti',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/Walkboy',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/rookit',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/CandyFm',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/NoiseBot',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/lastfm-simple-scrobble-client',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/lastfm-java',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/HypnosMusicPlayer',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/The-fm',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/material-player',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/LloydsPOC',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/harmony',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/MusicPlayer',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/TypeaheadSearch',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/MusicApp',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/FMManager',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/Music_Searcher_Test-for-Wipro',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/music',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/resumeSite',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/musicbrainz-android',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/Muzik',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/MyMusicPlayer',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/SongFinder',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/project',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/srimusic-java',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/Scrobblit',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/MagicCharts',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/DondaChanter',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/MarritLeenstra-pset3_2',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/Onix',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/IpodLastfmScrobbler',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/mymusic',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/LastFMAPI',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/MusicPlayer-using-MVC',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/TicktockMusic',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/SohanCodingTest',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/Teamproject',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/widgr',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/calendar-events-processor',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/google',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/project-in-house',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/OdonTO-DO',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/isst-proy',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/google-api-java-client-samples',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/myexperiments',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/ngcalsync',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/Hybrid-App-Web',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/Whirlpool_Android',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/Starbucks-Schedule-Importer',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Ptesting',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Gestion_De_Stock',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/.ipynb_checkpoints',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/ImageSearch',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/SpringSocialFlickr',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Gestionstock',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/AndroidNetworking_Ass',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/PhotoGalleryModified',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/flickr-api',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/JHgallery',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/structured-topics',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/InstagramLow',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/api_stock_management',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/GestionDeStockMvc',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/GestiondeStock',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/VARpedia',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/PhotoGalleryWithRxJava',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/flickroauth',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/FlickrLiker',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Gestion_de_stock',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Flickr_App_TDAM_FRC_UTN',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/MyWorkAndAssignments',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/oop_nlp',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Photography',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Spring-Boot',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Lab4_Android_Networking',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/flickr',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/flickr_json_app',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Wallpaper',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/CleanItApp',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/MBFlickrDemo',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Projetos-De-Faculdade',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/BigPicture',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/flickrfindr',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/igrisca',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/PruebaJava',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/gestion-bancaire-master',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/epicture',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/MobileOS',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/gestion_stock',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/photosearchapp',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/TestAIA',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Sales-Managements',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/OktaFlickrSpringIntegration_backend',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/stock_management',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/flickr-service',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/PhotosApp',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/mediasynchronizer',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/flicking',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/webService',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Wallpaper_Portal',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/PhotoFlickr',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/GestionDeStock',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/J4DataScience',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Machine-Learning-End-to-Endguide-for-Java-developers',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/TDAM_TPI',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/RetrofitFlickrAPI',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/tuto_GET',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/stockmanagement-backend',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/MemoryGame',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/GestionStock',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Journeys',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/projektyStudia',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/gestionStock',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/WallpaperFlicker',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/newMediaLab',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/WallpaperAppByDucMinh',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/FlickrList',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/backend-Ecommerce',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Shakalgram',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/StegHash',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/flickr-groups',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/kubernetes-example-application',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/flicloader',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/book-iot-for-javadeveloper',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/carl-bot',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/AndroidAssessment',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/phoenix',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/twitter_app',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/.ipynb_checkpoints',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/twitter-app',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/onesaitplatform-revoluiton-blockchain',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/beunique',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/twitter-bubbles',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/social-searcher',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/spring-twitter-stream',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/twitter_streaming_elk',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/twitter4j-patched',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/TwitterLab',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/ara-twitter',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/spring-social-twitter',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/Indian-Premier-League-Data-Analysis',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/MOCAD',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/GraphFromTwitterFollowers',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/TwitterObserver',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/Twitter-Bot',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/awt',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/WebsiteSchema',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/onesaitplatform-revolution-team-work3',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/DSMS_Project',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/TwitterCodingChallenge',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/twitter4j',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/sentimentAnalysis',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/websiteschema',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/project-bigData',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/cz4034-Grp2-2019s2',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/LetsMine',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/DS_Practica3',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/SpringSocial',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/lab0-twitter-rest',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/bds_project_workspace',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/LoginSocialNetwork',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/sdn-twitter-graph',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/twitter-services',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/butterfly-effect-stocks',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/onesaitplatform-revolution-dem',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/heckenlights',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/tweeter-kafka-spark-streaming',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/TwitchArchiver',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/bell-twitter-bot',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/geotweeter-for-android',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/twitter-dashboard-hdp',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/twithub',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/oauthhing-with-twitter',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/twitter-poll-app',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/community_detection_evolution',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/Twidere-Android-App',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/IF4072-SentimentAnalyser',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/mephi-dsbda-2020-hw3-stream-api',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/KisanNetwork',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/PittsburgMessenger',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/linkedin-java',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/twilio-quarkus',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/.ipynb_checkpoints',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/WildFire',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/twilio-java',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/dreamVoiceCalling',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/globalhack',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/JavaCode',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/conversations',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/Orienteer',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/DDS_Parcial',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/JavaTwSamples',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/Twilio API',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/Phase2_Submission_from_laptop',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/test-project-consume-jwt-kotlin-lombok-loadcsv',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/IMS',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/OwlMessaging',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/Pi-dev-bibliotheque2.0',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/RedHorizonVBR',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/twilio',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/twilio-demo',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/eclipse-workspace',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/sms_java',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/CatFactsAAS',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/intMautic',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/riot_twilio',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/api-snippets',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/hubspot-java-client',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/conference-broadcast-spark',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/SeleniumBasics',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/ShukDashboardBack',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/Message',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/smsapp-googlefirebase',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/ApiTutorial',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/Fire-Alarm-System',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/twilio_voice',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/mobilePidev',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/AirlineInDistressSignal',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/jibx-bindings',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/apiTest',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/Android_Practice',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/MyAPI',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/spacedog-server',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/SMSActivation',
 '/root//preprocessed/all_preproceeed_codes_by_url/SoundCloud API/SiteExtractor',
 '/root//preprocessed/all_preproceeed_codes_by_url/SoundCloud API/Amazon-Youtube-Player',
 '/root//preprocessed/all_preproceeed_codes_by_url/SoundCloud API/-SoundCloud-Java-API',
 '/root//preprocessed/all_preproceeed_codes_by_url/SoundCloud API/.ipynb_checkpoints',
 '/root//preprocessed/all_preproceeed_codes_by_url/SoundCloud API/inospeech',

In [9]:
test_rep

['/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/fm API',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/ntua-Multimedia',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/Throwback',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/heosnotifscrobbler',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/last-fm-java-crawler',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/Isel-Projects',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/M.A.D-Player',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/playlist-bot',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/App-music',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/AudioPlayer',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/aTunes',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/Last.fm API',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/audio_player_dev_mobile',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/angler',
 '/root//preprocessed/all_preproceeed_codes_by_url/Last.fm API/mediabrainz-java',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/gerenciador',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/google-api-libs',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/sra-project',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Calendar/google-calendar-poc',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/gestion-de-stock-backend',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/SpringComplet',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/proyectoPPII',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Flickr-Android',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/InventoryManagement',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/HelixiosWall',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Flickr-Findr',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/GestionPaieSpring',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Java-for-Data-Science',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/googleMap',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/imedia24Test',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/GestionStockSpringBoot',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/int20h',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/PostsApp',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/flickr_gui',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/festive-road-tagging',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/studies',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/camerstock',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/Gestion_stock_MVC',
 '/root//preprocessed/all_preproceeed_codes_by_url/Flickr API/PhotoGalleryMVVM',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/TMDAD-5maquinas',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/minianalytics',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/moodRing',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/wp-twitter-bot',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/onesaitplatform-revolution-aut-2',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/twitter-miner-v2',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/TwitterGraphTest',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/circle-ci',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/bigfarmathchallenge',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/JavaPractice',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/dispatcher',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/misc',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/twitter-search-client',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twitter API/message-gateway',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/Chiron-framework',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/SmartTruck',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/sms-blast',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/twilio-client',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/dslink-java-v2-twilio',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/interviews',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/ecosystemmobile',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/Mobile',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/twilio-twilio-java',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/user_review_tracker',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/halyard',
 '/root//preprocessed/all_preproceeed_codes_by_url/Twilio API/Coffee-Run',
 '/root//preprocessed/all_preproceeed_codes_by_url/SoundCloud API/pipextract',
 '/root//preprocessed/all_preproceeed_codes_by_url/SoundCloud API/FreeMusicPlayer',
 '/root//preprocessed/all_preproceeed_codes_by_url/SoundCloud API/NewPipeExtractorDTube',
 '/root//preprocessed/all_preproceeed_codes_by_url/SoundCloud API/RockolApp',
 '/root//preprocessed/all_preproceeed_codes_by_url/SoundCloud API/OneTapVideoDownload',
 '/root//preprocessed/all_preproceeed_codes_by_url/SoundCloud API/NewPipeExtractor',
 '/root//preprocessed/all_preproceeed_codes_by_url/SoundCloud API/IbeatBox',
 '/root//preprocessed/all_preproceeed_codes_by_url/SoundCloud API/youtubedl',
 '/root//preprocessed/all_preproceeed_codes_by_url/SoundCloud API/java-api-wrapper',
 '/root//preprocessed/all_preproceeed_codes_by_url/SoundCloud API/Macden-sDigitalRadio',
 '/root//preprocessed/all_preproceeed_codes_by_url/SoundCloud API/instantsonar',
 '/root//preprocessed/all_preproceeed_codes_by_url/Wikipedia API/bliki-kernel',
 '/root//preprocessed/all_preproceeed_codes_by_url/Wikipedia API/csa-final-project',
 '/root//preprocessed/all_preproceeed_codes_by_url/Wikipedia API/wiki-image-search',
 '/root//preprocessed/all_preproceeed_codes_by_url/Wikipedia API/jwbf',
 '/root//preprocessed/all_preproceeed_codes_by_url/Wikipedia API/Wiki-Degrees',
 '/root//preprocessed/all_preproceeed_codes_by_url/Wikipedia API/apps-android-wikipedia',
 '/root//preprocessed/all_preproceeed_codes_by_url/Wikipedia API/Wikimania',
 '/root//preprocessed/all_preproceeed_codes_by_url/Wikipedia API/Wiki-Association',
 '/root//preprocessed/all_preproceeed_codes_by_url/Wikipedia API/wlj-place-test',
 '/root//preprocessed/all_preproceeed_codes_by_url/Wikipedia API/WikiExtraction',
 '/root//preprocessed/all_preproceeed_codes_by_url/Wikipedia API/leetcode',
 '/root//preprocessed/all_preproceeed_codes_by_url/Wikipedia API/random-wiki-article',
 '/root//preprocessed/all_preproceeed_codes_by_url/Wikipedia API/nlp-starter',
 '/root//preprocessed/all_preproceeed_codes_by_url/YouTube API/geoyoutube-back',
 '/root//preprocessed/all_preproceeed_codes_by_url/YouTube API/YoutubeVidGame',
 '/root//preprocessed/all_preproceeed_codes_by_url/YouTube API/youtube-api',
 '/root//preprocessed/all_preproceeed_codes_by_url/YouTube API/how-to-subscribe-youtube-channel-in-android-app',
 '/root//preprocessed/all_preproceeed_codes_by_url/YouTube API/JSwaggerMaker',
 '/root//preprocessed/all_preproceeed_codes_by_url/YouTube API/measy-spotify-client',
 '/root//preprocessed/all_preproceeed_codes_by_url/YouTube API/MediaServiceCore',
 '/root//preprocessed/all_preproceeed_codes_by_url/YouTube API/Youtube-Desktop',
 '/root//preprocessed/all_preproceeed_codes_by_url/YouTube API/content-hub-adapter-youtube',
 '/root//preprocessed/all_preproceeed_codes_by_url/YouTube API/ML',
 '/root//preprocessed/all_preproceeed_codes_by_url/YouTube API/Listen2Youtube',
 '/root//preprocessed/all_preproceeed_codes_by_url/YouTube API/utube-android',
 '/root//preprocessed/all_preproceeed_codes_by_url/YouTube API/prodr',
 '/root//preprocessed/all_preproceeed_codes_by_url/YouTube API/YouTubeLite',
 '/root//preprocessed/all_preproceeed_codes_by_url/YouTube API/hakwonband-web',
 '/root//preprocessed/all_preproceeed_codes_by_url/YouTube API/flowedu-api',
 '/root//preprocessed/all_preproceeed_codes_by_url/YouTube API/postamatik',
 '/root//preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/osm-tools',
 '/root//preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/myStreetComplete',
 '/root//preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/Osmand-master',
 '/root//preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/AndroidApp',
 '/root//preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/mapAR',
 '/root//preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/laboratorio',
 '/root//preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/JOSMA',
 '/root//preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/OpenStreetMap API',
 '/root//preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/OpenMaps',
 '/root//preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/CyclosApp',
 '/root//preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/osmeditor4android',
 '/root//preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/HTW-GeoList',
 '/root//preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/M08NoteMap',
 '/root//preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/Maps',
 '/root//preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/Josm',
 '/root//preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/Geddit',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Maps API/bikerapm',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Maps API/hack-backend',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Maps API/OtherRoute',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Maps API/location-service',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Maps API/Scheduling-public-transport-Android-App',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Maps API/CommonApp',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Maps API/FXMaps',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Maps API/Lorflam',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Maps API/rentadrone',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Maps API/Concordia-Campus-Guide',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Maps API/shops-near-you-api',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Maps API/chatga-ride-driver',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Maps API/PlaylistGen',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Maps API/Microservices_Training',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Maps API/roadrunner',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Maps API/CoCeSo',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Maps API/cab-management-portal',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Maps API/google-step-internship-2020',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Maps API/hcpospoc',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Maps API/DirectionsApiJavaSample',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Maps API/chatga_ride_app',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google Maps API/rest-shops-near-you',
 '/root//preprocessed/all_preproceeed_codes_by_url/Facebook API/rest-api-java-master',
 '/root//preprocessed/all_preproceeed_codes_by_url/Facebook API/social_er',
 '/root//preprocessed/all_preproceeed_codes_by_url/Facebook API/MIEI',
 '/root//preprocessed/all_preproceeed_codes_by_url/Facebook API/WebStories',
 '/root//preprocessed/all_preproceeed_codes_by_url/Facebook API/facebook4j',
 '/root//preprocessed/all_preproceeed_codes_by_url/Facebook API/Facebook-Java-Ads-API',
 '/root//preprocessed/all_preproceeed_codes_by_url/Facebook API/test_project_forJenkins',
 '/root//preprocessed/all_preproceeed_codes_by_url/Facebook API/Your-host-home-java',
 '/root//preprocessed/all_preproceeed_codes_by_url/Facebook API/TriPory',
 '/root//preprocessed/all_preproceeed_codes_by_url/Facebook API/spring-social',
 '/root//preprocessed/all_preproceeed_codes_by_url/Facebook API/facebook-photos-exporting',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google App Engine API/WebAndCloud',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google App Engine API/webandcloudM1',
 '/root//preprocessed/all_preproceeed_codes_by_url/Google App Engine API/solutions-mobile-backend-starter-java',
 '/root//preprocessed/all_preproceeed_codes_by_url/Instagram Graph API/scrap-news-to-telegram-channel',
 '/root//preprocessed/all_preproceeed_codes_by_url/Instagram Graph API/cishell-plugins',
 '/root//preprocessed/all_preproceeed_codes_by_url/Instagram Graph API/SociVerse',
 '/root//preprocessed/all_preproceeed_codes_by_url/Instagram Graph API/spring-security-oauth',
 '/root//preprocessed/all_preproceeed_codes_by_url/Instagram Graph API/insta_bot',
 '/root//preprocessed/all_preproceeed_codes_by_url/Instagram Graph API/insta-on',
 '/root//preprocessed/all_preproceeed_codes_by_url/Instagram Graph API/SAESNEG',
 '/root//preprocessed/all_preproceeed_codes_by_url/Instagram Graph API/InstagramXBot',
 '/root//preprocessed/all_preproceeed_codes_by_url/Instagram Graph API/InstagramPostBot',
 '/root//preprocessed/all_preproceeed_codes_by_url/Instagram Graph API/apigee-android-sdk',
 '/root//preprocessed/all_preproceeed_codes_by_url/Amazon Product Advertising API/shopping-app',
 '/root//preprocessed/all_preproceeed_codes_by_url/Amazon Product Advertising API/apigateway',
 '/root//preprocessed/all_preproceeed_codes_by_url/Amazon Product Advertising API/Java-AWSS3-Sample-codes',
 '/root//preprocessed/all_preproceeed_codes_by_url/Amazon Product Advertising API/aws-sdk-sample-code-basic',
 '/root//preprocessed/all_preproceeed_codes_by_url/Amazon Product Advertising API/micropay',
 '/root//preprocessed/all_preproceeed_codes_by_url/Amazon Product Advertising API/cloudProject',
 '/root//preprocessed/all_preproceeed_codes_by_url/Amazon Product Advertising API/flapp',
 '/root//preprocessed/all_preproceeed_codes_by_url/Amazon Product Advertising API/aws-apigateway-sdk-java',
 '/root//preprocessed/all_preproceeed_codes_by_url/Amazon Product Advertising API/APIswager',
 '/root//preprocessed/all_preproceeed_codes_by_url/Amazon Product Advertising API/youtube-codes',
 '/root//preprocessed/all_preproceeed_codes_by_url/Amazon Product Advertising API/AWS-PDF-manipulator',
 '/root//preprocessed/all_preproceeed_codes_by_url/Amazon Product Advertising API/search-monster',
 '/root//preprocessed/all_preproceeed_codes_by_url/Amazon Product Advertising API/aws-project2',
 '/root//preprocessed/all_preproceeed_codes_by_url/Amazon Product Advertising API/idv-serverless',
 '/root//preprocessed/all_preproceeed_codes_by_url/LinkedIn API/oauthp5',
 '/root//preprocessed/all_preproceeed_codes_by_url/LinkedIn API/agorava-linkedin',
 '/root//preprocessed/all_preproceeed_codes_by_url/LinkedIn API/Dropmusic',
 '/root//preprocessed/all_preproceeed_codes_by_url/LinkedIn API/corso_java',
 '/root//preprocessed/all_preproceeed_codes_by_url/LinkedIn API/LinkedIn-SignIn',
 '/root//preprocessed/all_preproceeed_codes_by_url/LinkedIn API/SD_ucBusca',
 '/root//preprocessed/all_preproceeed_codes_by_url/LinkedIn API/SD-Meta-Final',
 '/root//preprocessed/all_preproceeed_codes_by_url/LinkedIn API/SelalF_final',
 '/root//preprocessed/all_preproceeed_codes_by_url/LinkedIn API/agroTransactional',
 '/root//preprocessed/all_preproceeed_codes_by_url/LinkedIn API/java-sample-application',
 '/root//preprocessed/all_preproceeed_codes_by_url/LinkedIn API/resumemaker',
 '/root//preprocessed/all_preproceeed_codes_by_url/LinkedIn API/oltu',
 '/root//preprocessed/all_preproceeed_codes_by_url/LinkedIn API/android-oauth-client']

In [10]:
import numpy as np
import pandas as pd

train_df_list_repo = pd.DataFrame(train_rep, columns = ['repo'])

In [15]:
train_df_list_repo.to_csv("/root/dcservcode_zh/scripts/0_2_preprocess/split_train_test/train_df_list_repo_18_jul.csv")
train_df_list_repo

                                                  repo
0    /root//preprocessed/all_preproceeed_codes_by_u...
1    /root//preprocessed/all_preproceeed_codes_by_u...
2    /root//preprocessed/all_preproceeed_codes_by_u...
3    /root//preprocessed/all_preproceeed_codes_by_u...
4    /root//preprocessed/all_preproceeed_codes_by_u...
..                                                 ...
738  /root//preprocessed/all_preproceeed_codes_by_u...
739  /root//preprocessed/all_preproceeed_codes_by_u...
740  /root//preprocessed/all_preproceeed_codes_by_u...
741  /root//preprocessed/all_preproceeed_codes_by_u...
742  /root//preprocessed/all_preproceeed_codes_by_u...

[743 rows x 1 columns]

In [17]:
test_df_list_repo = pd.DataFrame(test_rep, columns = ['repo'])

In [18]:
test_df_list_repo.to_csv("/root//dcservcode_zh/scripts/0_2_preprocess/split_train_test/test_df_list_repo18_jul.csv")
test_df_list_repo

                                                  repo
0    /root//preprocessed/all_preproceeed_codes_by_u...
1    /root//preprocessed/all_preproceeed_codes_by_u...
2    /root//preprocessed/all_preproceeed_codes_by_u...
3    /root//preprocessed/all_preproceeed_codes_by_u...
4    /root//preprocessed/all_preproceeed_codes_by_u...
..                                                 ...
190  /root//preprocessed/all_preproceeed_codes_by_u...
191  /root//preprocessed/all_preproceeed_codes_by_u...
192  /root//preprocessed/all_preproceeed_codes_by_u...
193  /root//preprocessed/all_preproceeed_codes_by_u...
194  /root//preprocessed/all_preproceeed_codes_by_u...

[195 rows x 1 columns]

##copy files

In [78]:
%cd  /content/drive/MyDrive/smartclide-project/code_api_/raw/

[Errno 2] No such file or directory: '/content/drive/MyDrive/smartclide-project/code_api_/raw/'
/root/dcservzh_git_last_version/dcservcode_zh/scripts/0_2_preprocess/split_train_test

In [79]:
!ls /content/drive/MyDrive/smartclide-project/code_api_/raw/

shell-init: error retrieving current directory: getcwd: cannot access parent directories: No such file or directory
ls: cannot access '/content/drive/MyDrive/smartclide-project/code_api_/raw/': No such file or directory

In [23]:
src=r"/root/preprocessed/all_preproceeed_codes_by_url"
des=r"/root/preprocessed/test_url_18_jul"

In [24]:
import os
des.split(os.path.sep)[-2]

'preprocessed'

In [26]:
import shutil
for item_path in test_rep:
  #  print(item_path)
        domain=item_path.split(os.path.sep)[-2]
        project=item_path.split(os.path.sep)[-1]
        s = src +"/"+ domain+"/"+project
        d = des +"/"+ domain+"/"+project
        print(s)
        print(d)
        print("-------------------------------------------")
        # if s.is_dir():
        #     copy_dir(s, d)
        # else:
        #     shutil.copy2(str(s), str(d))
       
        shutil.move( s,d)

/root/preprocessed/all_preproceeed_codes_by_url/Last.fm API/fm API
/root/preprocessed/test_url_18_jul/Last.fm API/fm API
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Last.fm API/ntua-Multimedia
/root/preprocessed/test_url_18_jul/Last.fm API/ntua-Multimedia
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Last.fm API/Throwback
/root/preprocessed/test_url_18_jul/Last.fm API/Throwback
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Last.fm API/heosnotifscrobbler
/root/preprocessed/test_url_18_jul/Last.fm API/heosnotifscrobbler
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Last.fm API/last-fm-java-crawler
/root/preprocessed/test_url_18_jul/Last.fm API/last-fm-java-crawler
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Last.fm API/Isel-Projects
/root/preprocessed/test_url_18_jul/Last.fm API/Isel-Projects
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Last.fm API/M.A.D-Player
/root/preprocessed/test_url_18_jul/Last.fm API/M.A.D-Player
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Last.fm API/playlist-bot
/root/preprocessed/test_url_18_jul/Last.fm API/playlist-bot
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Last.fm API/App-music
/root/preprocessed/test_url_18_jul/Last.fm API/App-music
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Last.fm API/AudioPlayer
/root/preprocessed/test_url_18_jul/Last.fm API/AudioPlayer
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Last.fm API/aTunes
/root/preprocessed/test_url_18_jul/Last.fm API/aTunes
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Last.fm API/Last.fm API
/root/preprocessed/test_url_18_jul/Last.fm API/Last.fm API
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Last.fm API/audio_player_dev_mobile
/root/preprocessed/test_url_18_jul/Last.fm API/audio_player_dev_mobile
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Last.fm API/angler
/root/preprocessed/test_url_18_jul/Last.fm API/angler
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Last.fm API/mediabrainz-java
/root/preprocessed/test_url_18_jul/Last.fm API/mediabrainz-java
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google Calendar/gerenciador
/root/preprocessed/test_url_18_jul/Google Calendar/gerenciador
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google Calendar/google-api-libs
/root/preprocessed/test_url_18_jul/Google Calendar/google-api-libs
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google Calendar/sra-project
/root/preprocessed/test_url_18_jul/Google Calendar/sra-project
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google Calendar/google-calendar-poc
/root/preprocessed/test_url_18_jul/Google Calendar/google-calendar-poc
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Flickr API/gestion-de-stock-backend
/root/preprocessed/test_url_18_jul/Flickr API/gestion-de-stock-backend
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Flickr API/SpringComplet
/root/preprocessed/test_url_18_jul/Flickr API/SpringComplet
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Flickr API/proyectoPPII
/root/preprocessed/test_url_18_jul/Flickr API/proyectoPPII
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Flickr API/Flickr-Android
/root/preprocessed/test_url_18_jul/Flickr API/Flickr-Android
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Flickr API/InventoryManagement
/root/preprocessed/test_url_18_jul/Flickr API/InventoryManagement
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Flickr API/HelixiosWall
/root/preprocessed/test_url_18_jul/Flickr API/HelixiosWall
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Flickr API/Flickr-Findr
/root/preprocessed/test_url_18_jul/Flickr API/Flickr-Findr
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Flickr API/GestionPaieSpring
/root/preprocessed/test_url_18_jul/Flickr API/GestionPaieSpring
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Flickr API/Java-for-Data-Science
/root/preprocessed/test_url_18_jul/Flickr API/Java-for-Data-Science
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Flickr API/googleMap
/root/preprocessed/test_url_18_jul/Flickr API/googleMap
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Flickr API/imedia24Test
/root/preprocessed/test_url_18_jul/Flickr API/imedia24Test
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Flickr API/GestionStockSpringBoot
/root/preprocessed/test_url_18_jul/Flickr API/GestionStockSpringBoot
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Flickr API/int20h
/root/preprocessed/test_url_18_jul/Flickr API/int20h
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Flickr API/PostsApp
/root/preprocessed/test_url_18_jul/Flickr API/PostsApp
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Flickr API/flickr_gui
/root/preprocessed/test_url_18_jul/Flickr API/flickr_gui
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Flickr API/festive-road-tagging
/root/preprocessed/test_url_18_jul/Flickr API/festive-road-tagging
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Flickr API/studies
/root/preprocessed/test_url_18_jul/Flickr API/studies
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Flickr API/camerstock
/root/preprocessed/test_url_18_jul/Flickr API/camerstock
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Flickr API/Gestion_stock_MVC
/root/preprocessed/test_url_18_jul/Flickr API/Gestion_stock_MVC
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Flickr API/PhotoGalleryMVVM
/root/preprocessed/test_url_18_jul/Flickr API/PhotoGalleryMVVM
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Twitter API/TMDAD-5maquinas
/root/preprocessed/test_url_18_jul/Twitter API/TMDAD-5maquinas
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Twitter API/minianalytics
/root/preprocessed/test_url_18_jul/Twitter API/minianalytics
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Twitter API/moodRing
/root/preprocessed/test_url_18_jul/Twitter API/moodRing
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Twitter API/wp-twitter-bot
/root/preprocessed/test_url_18_jul/Twitter API/wp-twitter-bot
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Twitter API/onesaitplatform-revolution-aut-2
/root/preprocessed/test_url_18_jul/Twitter API/onesaitplatform-revolution-aut-2
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Twitter API/twitter-miner-v2
/root/preprocessed/test_url_18_jul/Twitter API/twitter-miner-v2
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Twitter API/TwitterGraphTest
/root/preprocessed/test_url_18_jul/Twitter API/TwitterGraphTest
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Twitter API/circle-ci
/root/preprocessed/test_url_18_jul/Twitter API/circle-ci
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Twitter API/bigfarmathchallenge
/root/preprocessed/test_url_18_jul/Twitter API/bigfarmathchallenge
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Twitter API/JavaPractice
/root/preprocessed/test_url_18_jul/Twitter API/JavaPractice
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Twitter API/dispatcher
/root/preprocessed/test_url_18_jul/Twitter API/dispatcher
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Twitter API/misc
/root/preprocessed/test_url_18_jul/Twitter API/misc
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Twitter API/twitter-search-client
/root/preprocessed/test_url_18_jul/Twitter API/twitter-search-client
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Twitter API/message-gateway
/root/preprocessed/test_url_18_jul/Twitter API/message-gateway
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Twilio API/Chiron-framework
/root/preprocessed/test_url_18_jul/Twilio API/Chiron-framework
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Twilio API/SmartTruck
/root/preprocessed/test_url_18_jul/Twilio API/SmartTruck
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Twilio API/sms-blast
/root/preprocessed/test_url_18_jul/Twilio API/sms-blast
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Twilio API/twilio-client
/root/preprocessed/test_url_18_jul/Twilio API/twilio-client
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Twilio API/dslink-java-v2-twilio
/root/preprocessed/test_url_18_jul/Twilio API/dslink-java-v2-twilio
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Twilio API/interviews
/root/preprocessed/test_url_18_jul/Twilio API/interviews
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Twilio API/ecosystemmobile
/root/preprocessed/test_url_18_jul/Twilio API/ecosystemmobile
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Twilio API/Mobile
/root/preprocessed/test_url_18_jul/Twilio API/Mobile
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Twilio API/twilio-twilio-java
/root/preprocessed/test_url_18_jul/Twilio API/twilio-twilio-java
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Twilio API/user_review_tracker
/root/preprocessed/test_url_18_jul/Twilio API/user_review_tracker
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Twilio API/halyard
/root/preprocessed/test_url_18_jul/Twilio API/halyard
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Twilio API/Coffee-Run
/root/preprocessed/test_url_18_jul/Twilio API/Coffee-Run
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/SoundCloud API/pipextract
/root/preprocessed/test_url_18_jul/SoundCloud API/pipextract
-------------------------------------------

/root/preprocessed/all_preproceeed_codes_by_url/SoundCloud API/FreeMusicPlayer
/root/preprocessed/test_url_18_jul/SoundCloud API/FreeMusicPlayer
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/SoundCloud API/NewPipeExtractorDTube
/root/preprocessed/test_url_18_jul/SoundCloud API/NewPipeExtractorDTube
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/SoundCloud API/RockolApp
/root/preprocessed/test_url_18_jul/SoundCloud API/RockolApp
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/SoundCloud API/OneTapVideoDownload
/root/preprocessed/test_url_18_jul/SoundCloud API/OneTapVideoDownload
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/SoundCloud API/NewPipeExtractor
/root/preprocessed/test_url_18_jul/SoundCloud API/NewPipeExtractor
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/SoundCloud API/IbeatBox
/root/preprocessed/test_url_18_jul/SoundCloud API/IbeatBox
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/SoundCloud API/youtubedl
/root/preprocessed/test_url_18_jul/SoundCloud API/youtubedl
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/SoundCloud API/java-api-wrapper
/root/preprocessed/test_url_18_jul/SoundCloud API/java-api-wrapper
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/SoundCloud API/Macden-sDigitalRadio
/root/preprocessed/test_url_18_jul/SoundCloud API/Macden-sDigitalRadio
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/SoundCloud API/instantsonar
/root/preprocessed/test_url_18_jul/SoundCloud API/instantsonar
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Wikipedia API/bliki-kernel
/root/preprocessed/test_url_18_jul/Wikipedia API/bliki-kernel
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Wikipedia API/csa-final-project
/root/preprocessed/test_url_18_jul/Wikipedia API/csa-final-project
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Wikipedia API/wiki-image-search
/root/preprocessed/test_url_18_jul/Wikipedia API/wiki-image-search
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Wikipedia API/jwbf
/root/preprocessed/test_url_18_jul/Wikipedia API/jwbf
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Wikipedia API/Wiki-Degrees
/root/preprocessed/test_url_18_jul/Wikipedia API/Wiki-Degrees
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Wikipedia API/apps-android-wikipedia
/root/preprocessed/test_url_18_jul/Wikipedia API/apps-android-wikipedia
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Wikipedia API/Wikimania
/root/preprocessed/test_url_18_jul/Wikipedia API/Wikimania
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Wikipedia API/Wiki-Association
/root/preprocessed/test_url_18_jul/Wikipedia API/Wiki-Association
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Wikipedia API/wlj-place-test
/root/preprocessed/test_url_18_jul/Wikipedia API/wlj-place-test
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Wikipedia API/WikiExtraction
/root/preprocessed/test_url_18_jul/Wikipedia API/WikiExtraction
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Wikipedia API/leetcode
/root/preprocessed/test_url_18_jul/Wikipedia API/leetcode
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Wikipedia API/random-wiki-article
/root/preprocessed/test_url_18_jul/Wikipedia API/random-wiki-article
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Wikipedia API/nlp-starter
/root/preprocessed/test_url_18_jul/Wikipedia API/nlp-starter
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/YouTube API/geoyoutube-back
/root/preprocessed/test_url_18_jul/YouTube API/geoyoutube-back
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/YouTube API/YoutubeVidGame
/root/preprocessed/test_url_18_jul/YouTube API/YoutubeVidGame
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/YouTube API/youtube-api
/root/preprocessed/test_url_18_jul/YouTube API/youtube-api
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/YouTube API/how-to-subscribe-youtube-channel-in-android-app
/root/preprocessed/test_url_18_jul/YouTube API/how-to-subscribe-youtube-channel-in-android-app
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/YouTube API/JSwaggerMaker
/root/preprocessed/test_url_18_jul/YouTube API/JSwaggerMaker
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/YouTube API/measy-spotify-client
/root/preprocessed/test_url_18_jul/YouTube API/measy-spotify-client
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/YouTube API/MediaServiceCore
/root/preprocessed/test_url_18_jul/YouTube API/MediaServiceCore
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/YouTube API/Youtube-Desktop
/root/preprocessed/test_url_18_jul/YouTube API/Youtube-Desktop
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/YouTube API/content-hub-adapter-youtube
/root/preprocessed/test_url_18_jul/YouTube API/content-hub-adapter-youtube
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/YouTube API/ML
/root/preprocessed/test_url_18_jul/YouTube API/ML
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/YouTube API/Listen2Youtube
/root/preprocessed/test_url_18_jul/YouTube API/Listen2Youtube
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/YouTube API/utube-android
/root/preprocessed/test_url_18_jul/YouTube API/utube-android
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/YouTube API/prodr
/root/preprocessed/test_url_18_jul/YouTube API/prodr
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/YouTube API/YouTubeLite
/root/preprocessed/test_url_18_jul/YouTube API/YouTubeLite
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/YouTube API/hakwonband-web
/root/preprocessed/test_url_18_jul/YouTube API/hakwonband-web
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/YouTube API/flowedu-api
/root/preprocessed/test_url_18_jul/YouTube API/flowedu-api
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/YouTube API/postamatik
/root/preprocessed/test_url_18_jul/YouTube API/postamatik
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/osm-tools
/root/preprocessed/test_url_18_jul/OpenStreetMap API/osm-tools
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/myStreetComplete
/root/preprocessed/test_url_18_jul/OpenStreetMap API/myStreetComplete
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/Osmand-master
/root/preprocessed/test_url_18_jul/OpenStreetMap API/Osmand-master
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/AndroidApp
/root/preprocessed/test_url_18_jul/OpenStreetMap API/AndroidApp
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/mapAR
/root/preprocessed/test_url_18_jul/OpenStreetMap API/mapAR
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/laboratorio
/root/preprocessed/test_url_18_jul/OpenStreetMap API/laboratorio
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/JOSMA
/root/preprocessed/test_url_18_jul/OpenStreetMap API/JOSMA
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/OpenStreetMap API
/root/preprocessed/test_url_18_jul/OpenStreetMap API/OpenStreetMap API
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/OpenMaps
/root/preprocessed/test_url_18_jul/OpenStreetMap API/OpenMaps
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/CyclosApp
/root/preprocessed/test_url_18_jul/OpenStreetMap API/CyclosApp
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/osmeditor4android
/root/preprocessed/test_url_18_jul/OpenStreetMap API/osmeditor4android
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/HTW-GeoList
/root/preprocessed/test_url_18_jul/OpenStreetMap API/HTW-GeoList
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/M08NoteMap
/root/preprocessed/test_url_18_jul/OpenStreetMap API/M08NoteMap
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/Maps
/root/preprocessed/test_url_18_jul/OpenStreetMap API/Maps
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/Josm
/root/preprocessed/test_url_18_jul/OpenStreetMap API/Josm
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/OpenStreetMap API/Geddit
/root/preprocessed/test_url_18_jul/OpenStreetMap API/Geddit
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google Maps API/bikerapm
/root/preprocessed/test_url_18_jul/Google Maps API/bikerapm
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google Maps API/hack-backend
/root/preprocessed/test_url_18_jul/Google Maps API/hack-backend
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google Maps API/OtherRoute
/root/preprocessed/test_url_18_jul/Google Maps API/OtherRoute
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google Maps API/location-service
/root/preprocessed/test_url_18_jul/Google Maps API/location-service
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google Maps API/Scheduling-public-transport-Android-App
/root/preprocessed/test_url_18_jul/Google Maps API/Scheduling-public-transport-Android-App
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google Maps API/CommonApp
/root/preprocessed/test_url_18_jul/Google Maps API/CommonApp
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google Maps API/FXMaps
/root/preprocessed/test_url_18_jul/Google Maps API/FXMaps
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google Maps API/Lorflam
/root/preprocessed/test_url_18_jul/Google Maps API/Lorflam
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google Maps API/rentadrone
/root/preprocessed/test_url_18_jul/Google Maps API/rentadrone
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google Maps API/Concordia-Campus-Guide
/root/preprocessed/test_url_18_jul/Google Maps API/Concordia-Campus-Guide
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google Maps API/shops-near-you-api
/root/preprocessed/test_url_18_jul/Google Maps API/shops-near-you-api
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google Maps API/chatga-ride-driver
/root/preprocessed/test_url_18_jul/Google Maps API/chatga-ride-driver
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google Maps API/PlaylistGen
/root/preprocessed/test_url_18_jul/Google Maps API/PlaylistGen
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google Maps API/Microservices_Training
/root/preprocessed/test_url_18_jul/Google Maps API/Microservices_Training
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google Maps API/roadrunner
/root/preprocessed/test_url_18_jul/Google Maps API/roadrunner
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google Maps API/CoCeSo
/root/preprocessed/test_url_18_jul/Google Maps API/CoCeSo
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google Maps API/cab-management-portal
/root/preprocessed/test_url_18_jul/Google Maps API/cab-management-portal
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google Maps API/google-step-internship-2020
/root/preprocessed/test_url_18_jul/Google Maps API/google-step-internship-2020
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google Maps API/hcpospoc
/root/preprocessed/test_url_18_jul/Google Maps API/hcpospoc
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google Maps API/DirectionsApiJavaSample
/root/preprocessed/test_url_18_jul/Google Maps API/DirectionsApiJavaSample
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google Maps API/chatga_ride_app
/root/preprocessed/test_url_18_jul/Google Maps API/chatga_ride_app
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google Maps API/rest-shops-near-you
/root/preprocessed/test_url_18_jul/Google Maps API/rest-shops-near-you
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Facebook API/rest-api-java-master
/root/preprocessed/test_url_18_jul/Facebook API/rest-api-java-master
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Facebook API/social_er
/root/preprocessed/test_url_18_jul/Facebook API/social_er
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Facebook API/MIEI
/root/preprocessed/test_url_18_jul/Facebook API/MIEI
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Facebook API/WebStories
/root/preprocessed/test_url_18_jul/Facebook API/WebStories
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Facebook API/facebook4j
/root/preprocessed/test_url_18_jul/Facebook API/facebook4j
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Facebook API/Facebook-Java-Ads-API
/root/preprocessed/test_url_18_jul/Facebook API/Facebook-Java-Ads-API
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Facebook API/test_project_forJenkins
/root/preprocessed/test_url_18_jul/Facebook API/test_project_forJenkins
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Facebook API/Your-host-home-java
/root/preprocessed/test_url_18_jul/Facebook API/Your-host-home-java
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Facebook API/TriPory
/root/preprocessed/test_url_18_jul/Facebook API/TriPory
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Facebook API/spring-social
/root/preprocessed/test_url_18_jul/Facebook API/spring-social
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Facebook API/facebook-photos-exporting
/root/preprocessed/test_url_18_jul/Facebook API/facebook-photos-exporting
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google App Engine API/WebAndCloud
/root/preprocessed/test_url_18_jul/Google App Engine API/WebAndCloud
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google App Engine API/webandcloudM1
/root/preprocessed/test_url_18_jul/Google App Engine API/webandcloudM1
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Google App Engine API/solutions-mobile-backend-starter-java
/root/preprocessed/test_url_18_jul/Google App Engine API/solutions-mobile-backend-starter-java
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Instagram Graph API/scrap-news-to-telegram-channel
/root/preprocessed/test_url_18_jul/Instagram Graph API/scrap-news-to-telegram-channel
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Instagram Graph API/cishell-plugins
/root/preprocessed/test_url_18_jul/Instagram Graph API/cishell-plugins
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Instagram Graph API/SociVerse
/root/preprocessed/test_url_18_jul/Instagram Graph API/SociVerse
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Instagram Graph API/spring-security-oauth
/root/preprocessed/test_url_18_jul/Instagram Graph API/spring-security-oauth
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Instagram Graph API/insta_bot
/root/preprocessed/test_url_18_jul/Instagram Graph API/insta_bot
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Instagram Graph API/insta-on
/root/preprocessed/test_url_18_jul/Instagram Graph API/insta-on
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Instagram Graph API/SAESNEG
/root/preprocessed/test_url_18_jul/Instagram Graph API/SAESNEG
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Instagram Graph API/InstagramXBot
/root/preprocessed/test_url_18_jul/Instagram Graph API/InstagramXBot
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Instagram Graph API/InstagramPostBot
/root/preprocessed/test_url_18_jul/Instagram Graph API/InstagramPostBot
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Instagram Graph API/apigee-android-sdk
/root/preprocessed/test_url_18_jul/Instagram Graph API/apigee-android-sdk
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Amazon Product Advertising API/shopping-app
/root/preprocessed/test_url_18_jul/Amazon Product Advertising API/shopping-app
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Amazon Product Advertising API/apigateway
/root/preprocessed/test_url_18_jul/Amazon Product Advertising API/apigateway
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Amazon Product Advertising API/Java-AWSS3-Sample-codes
/root/preprocessed/test_url_18_jul/Amazon Product Advertising API/Java-AWSS3-Sample-codes
-------------------------------------------
/root/preprocessed/all_preproceeed_codes_by_url/Amazon Product Advertising API/aws-sdk-sample-code-basic

In [1]:
%cd /content/drive/MyDrive/smartclide-project/code_api_/raw/train/

[Errno 2] No such file or directory: '/content/drive/MyDrive/smartclide-project/code_api_/raw/train/'
/content

In [ ]:
# !find . -type d -empty -print -delete